version: "3"


services:
  db:
    image: postgres
  backend:
    build: ./backend
    volumes:
      - ./backend/:/backend
    working_dir: /backend/
    command: uwsgi --master --ini uwsgi.ini
    ports:
      - 8000:8000
    depends_on:
      - db
#      - worker
  frontend:
    image: node:latest
    command: sh entrypoint.sh
    working_dir: /frontend
    volumes:
      - ./frontend/:/frontend
    ports:
      - 3000:3000
  web:
    build:
      context: ./web/
    ports:
      - 80:8080
      - 443:443
    volumes:
      - ./frontend/build:/frontend
      - ./backend/static:/static
      - ./backend/media:/media
    depends_on:
      - backend
#  worker:
#    build:
#      context: ./worker/